#!/usr/bin/env bash

# Def vars

export RICETHEME=$(<$HOME/.config/bspwm/theme.cfg)
PATH="$HOME/.config/bspwm/scripts:$PATH"
bspdir="$HOME/.config/bspwm"
polydir="$HOME/.config/bspwm/themes/$RICETHEME/polybar"
export defnetif=$(ip route | grep '^default' | awk '{print $5}' | head -n1)

# You can edit this
BSPWM_BORDER='0'
BSPWM_GAP='5'

# Functions

function launch() {
  local running
  running="$(pgrep -x "$1")"
  [ "$running" ] && kill -9 $(pgrep -x $1) 2> /dev/null
  eval "$* &"
}

function killeww() {
  if [[ `pidof eww` ]]; then 
		pkill eww
  fi
}

function ReloadTerms() {
  cat $HOME/.config/bspwm/themes/$RICETHEME/alacrittyrc > $HOME/.config/alacritty/alacritty.yml
}

function SetBspwmConf() {
	bspc config border_width "$BSPWM_BORDER"
	bspc config top_padding "$2"
	bspc config bottom_padding "$3"
	bspc config normal_border_color "$4" 
	bspc config active_border_color "$5"
	bspc config focused_border_color "$6"
	bspc config presel_feedback_color "$7"
	bspc config left_padding "$8"
	bspc config right_padding "$9"
	bspc config window_gap "$BSPWM_GAP"
}

# Workspaces

workspaces() {
	name=0
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5'
		#bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5'
		#bspc monitor DP2 -n "1" -d '1' '2' '3' '4' '5'
		#bspc monitor DP2 -s ${monitor}
		let name++
	done
}

workspaces

# Launch The Rice

case $RICETHEME in
	
		theme1)
		
		  SetBspwmConf "$BSPWM_BORDER" 40 5 "#414868" "#c0caf5" "#bb9af7" "#7aa2f7" 5 5 "$BSPWM_GAP"
		  		  
		  killeww
		  launch polybar -q theme1-bar1 -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark 
		  
		  ;;

		theme2)
		
		  SetBspwmConf "$BSPWM_BORDER" 40 5 "#ca9ee6" "#ca9ee6" "#8CAAEE" "#E78284" 5 5 "$BSPWM_GAP"
		  
		  killeww
		  launch polybar -q theme2-bar1 -c ${polydir}/config.ini
		  polybar -q theme2-bar2 -c ${polydir}/config.ini &
		  polybar -q theme2-bar3 -c ${polydir}/config.ini &
		  launch dunst -config ${bspdir}/dunstrc-light
		  
		  ;;
		  
		theme3)
		
		  SetBspwmConf "$BSPWM_BORDER" 5 35 "#b8bfe5" "#b8bfe5" "#7560d3" "#81ae5f" 5 5 "$BSPWM_GAP" 
		  
		  killeww
		  launch polybar -q theme3-bar1 -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
		theme4)
		
		  SetBspwmConf "$BSPWM_BORDER" 15 0 "#d3869b" "#d3869b" "#fbf1c7" "#b8bb26" 0 0 "$BSPWM_GAP"

		  killeww
		  launch polybar -q theme4-bar1 -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
		theme5)
		
		  SetBspwmConf "$BSPWM_BORDER" 40 5 "#C574DD" "#C574DD" "#8897F4" "#FF4971" 5 5 "$BSPWM_GAP"
		  
		  killeww
		  launch polybar -q theme5-bar1 -c ${polydir}/config.ini
		  polybar -q theme5-bar2 -c ${polydir}/config.ini &
		  polybar -q theme5-bar3 -c ${polydir}/config.ini &
		  polybar -q theme5-bar4 -c ${polydir}/config.ini &
		  polybar -q theme5-bar5 -c ${polydir}/config.ini &
		  polybar -q theme5-bar6 -c ${polydir}/config.ini &
		  polybar -q theme5-bar7 -c ${polydir}/config.ini &
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
		theme6)
		
		  SetBspwmConf "$BSPWM_BORDER" 5 50 "#9bced7" "#9bced7" "#c3a5e6" "#c3a5e6" 5 5 "$BSPWM_GAP"
		  
		  killeww
		  launch polybar -q theme6-bar1 -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
	esac

# bspwm conf

bspc config external_rules_command ~/.config/bspwm/scripts/ExternalRules

bspc config single_monocle                true
bspc config split_ratio                   0.5
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config center_pseudo_tiled			  true

bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child

bspc config remove_disabled_monitors      true 
bspc config merge_overlapping_monitors    true

bspc config pointer_motion_interval       16

# AutoStart Apps

ReloadTerms
launch sxhkd -c ${bspdir}/sxhkdrc
launch picom --config ${bspdir}/themes/$RICETHEME/picom.conf
#launch picom --legacy-backends --config ${bspdir}/rices/$RICETHEME/picom.conf
	
if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

RandomWall
#nitrogen --restore &
xsetroot -cursor_name left_ptr

#install wmname for java apps
wmname LG3D