#!/usr/bin/env bash

#			Simple script to hide/unhide polybar

function hide() {
	
	if [[ "${RICETHEME}" == @(theme1|aline|silvia|pamela) ]]; then
		polybar-msg cmd hide | bspc config top_padding 5
		
	elif [[ "${RICETHEME}" == @(isabel|cristina) ]]; then
		polybar-msg cmd hide | bspc config bottom_padding 5
		
	else 
		echo "Error: Something fails dud.."
	fi
}

function unhide() {
	
	if [[ "${RICETHEME}" == @(theme1|pamela) ]]; then
		polybar-msg cmd show | bspc config top_padding 40
		
	elif [[ "${RICETHEME}" == aline ]]; then
		polybar-msg cmd show | bspc config top_padding 40
		
	elif [[ "${RICETHEME}" == silvia ]]; then
		polybar-msg cmd show | bspc config top_padding 35
		
	elif [[ "${RICETHEME}" == isabel ]]; then
		polybar-msg cmd show | bspc config bottom_padding 35
		
	elif [[ "${RICETHEME}" == cristina ]]; then
		polybar-msg cmd show | bspc config bottom_padding 50
		
	else 
		echo "Error: Something fails dud.."
		
	fi
}

   case $1 in
		-h | --hide | hide)
			hide
			exit;;
		-u | --unhide | unhide)
			unhide
			exit;;
			*) # Invalid option
         echo "Error: Invalid option"
         exit;;
   esac
